name: 2. Manual Github Release


on:
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch matches pattern
        run: |
          if ! echo "${{ github.ref_name }}" | grep -q "release/"; then
            echo "Branch name must match pattern 'release' (e.g. release/2.13.2)"
            exit 1
          fi

  call-publish-reusable:
    needs: check-branch
    uses: ./.github/workflows/publish-reusable.yml
    with:
      branch: ${{ github.ref_name }}
    secrets: inherit
