name: Common SDK publish RC manual


on:
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch matches pattern
        run: |
          echo "Checking if branch matches pattern"

  call-publish-reusable:
    needs: check-branch
    uses: ./.github/workflows/publish-reusable.yml
    with:
      branch: ${{ github.ref_name }}
    secrets: inherit
